"""Add final_price field

Revision ID: 6d225a4deb97
Revises: c81c1f1632a3
Create Date: 2025-05-20 17:36:18.112679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d225a4deb97'
down_revision: Union[str, None] = 'c81c1f1632a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_parts', sa.Column('final_price', sa.Float(), nullable=False, server_default='0.0'))
    op.alter_column("inventory_parts", "final_price", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_parts', 'final_price')
    # ### end Alembic commands ###
