"""Add is_active field

Revision ID: 96c11a61c56f
Revises: 56d101d713b7
Create Date: 2025-05-19 15:06:09.523026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c11a61c56f'
down_revision: Union[str, None] = '56d101d713b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('inventory_parts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('repair_order_parts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('repair_orders', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('vehicles', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    op.alter_column("customers", "is_active", server_default=None)
    op.alter_column("inventory_parts", "is_active", server_default=None)
    op.alter_column("repair_order_parts", "is_active", server_default=None)
    op.alter_column("repair_orders", "is_active", server_default=None)
    op.alter_column("vehicles", "is_active", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'is_active')
    op.drop_column('repair_orders', 'is_active')
    op.drop_column('repair_order_parts', 'is_active')
    op.drop_column('inventory_parts', 'is_active')
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###
