"""Add datetime fields

Revision ID: c7b296969fe6
Revises: 96c11a61c56f
Create Date: 2025-05-19 22:36:18.889237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b296969fe6'
down_revision: Union[str, None] = '96c11a61c56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_order_parts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('repair_order_parts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('repair_orders', sa.Column('date_in', sa.DateTime(), nullable=False))
    op.add_column('repair_orders', sa.Column('date_expected_out', sa.DateTime(), nullable=True))
    op.add_column('repair_orders', sa.Column('date_out', sa.DateTime(), nullable=True))
    op.add_column('repair_orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('repair_orders', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair_orders', 'updated_at')
    op.drop_column('repair_orders', 'created_at')
    op.drop_column('repair_orders', 'date_out')
    op.drop_column('repair_orders', 'date_expected_out')
    op.drop_column('repair_orders', 'date_in')
    op.drop_column('repair_order_parts', 'updated_at')
    op.drop_column('repair_order_parts', 'created_at')
    # ### end Alembic commands ###
